# 16.15.0-alpine3.15
FROM docker.io/library/node@sha256:bb776153f81d6e931211e3cadd7eef92c811e7086993b685d1f40242d486b9bb

WORKDIR /app

COPY package.json \
     yarn.lock ./
RUN yarn install

COPY public public
COPY src src

ENV REACT_APP_API=localhost:9090

CMD yarn start
