version: "3.9"

services:
  backend:
    build:
      context: api
      dockerfile: Containerfile
    environment:
      PORT: 3000
    restart: unless-stopped
  frontend:
    build:
      context: frontend
      dockerfile: Containerfile
      args:
        REACT_APP_API: devops.ivolga.tech
    restart: unless-stopped
  nginx:
    build:
      context: nginx
      dockerfile: Containerfile
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    restart: unless-stopped
