version: "3.9"

services:
  backend:
    build:
      context: api
      dockerfile: Containerfile
    environment:
      PORT: 5000
    network_mode: host
    restart: unless-stopped
  frontend:
    build:
      context: frontend
      dockerfile: Containerfile
      args:
        REACT_APP_API: devops.lvh.me
    network_mode: host
    restart: unless-stopped
  nginx:
    build:
      context: nginx
      dockerfile: Containerfile
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    network_mode: host
    restart: unless-stopped
