version: "3.9"

services:
  backend:
    build:
      context: api
      dockerfile: Containerfile
    environment:
      PORT: 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1s
    networks:
      - services
    restart: unless-stopped
  frontend:
    build:
      context: frontend
      dockerfile: Containerfile
      args:
        REACT_APP_API: devops.ivolga.tech
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1s
    networks:
      - services
    restart: unless-stopped
  nginx:
    build:
      context: nginx
      dockerfile: Containerfile
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1s
    networks:
      - services
      - nginx
    restart: unless-stopped

networks:
  services:
    internal: true
  nginx:
